pipeline {
    agent any
    
    options {
        scm {
            git {
                remote {
                    url 'https://github.com/Fateemaaa/mlopstask2.git'
                }
                branch 'main'
            }
        }
    }
    
    stages {
        stage('Build') {
            steps {
                bat 'pip install -r mlopstask2-main\\requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                bat 'python mlopstask2-main\\test_test.py'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'deployed'
            }
        }
    }
}
