pipeline {
    agent any
    
    options {
        scm {
            git {
                remote {
                    url 'https://github.com/Fateemaaa/mlopstask2.git'
                }
                branch 'main'
            }
        }
    }
    
    stages {
        stage('Build') {
            steps {
                dir('mlopstask2-main') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('mlopstask2-main') {
                    sh 'python3 test_test.py'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'deployed'
            }
        }
    }
}
